@startuml
skinparam linetype ortho


' Добавление скорой помощи и родственник (АПК)


' === Горизонтальное расположение ===
left to right direction

' === Определение объектов ===
actor "Пациент" as Patient #lightblue
actor "Врач" as Doctor #lightblue

rectangle "Имплантируемый датчик\n📡 Передача измерений глюкозы" as Sensor #lightblue
rectangle "Носимое устройство\n🚨 Звуковая и световая тревога\n📡 Отправка данных (каждые 4 часа)\n📶 Хранение данных без интернета" as Wearable #lightgray
rectangle "Мобильный телефон\n🔄 NFC передача данных\n⏩ Немедленная отправка на сервер" as Mobile #lightgreen
rectangle "Сервер\n🔍 Анализ данных\n📥 Сохранение в БД\n🔄 Обновление обработанных данных" as Server #lightcoral
database "База данных\n📦 Хранение всех данных" as DB #lightyellow
rectangle "ПК пациента\n📊 Графики, уведомления" as PatientPC #lightblue
rectangle "ПК врача\n📈 Анализ данных пациента" as DoctorPC #lightblue

rectangle "Скорая помощь" as HELP #lightblue

' === Связи ===
Sensor --> Wearable
Wearable --> Server
Wearable --> Mobile
Mobile --> Server
Server --> DB
Server --> PatientPC
Server --> DoctorPC
Server --> Mobile
PatientPC --> Patient
DoctorPC --> Doctor
Server --> HELP

@enduml
