@startuml
skinparam usecase {
    BackgroundColor LightBlue
    BorderColor DarkBlue
    FontColor Black
    FontSize 14
}

skinparam actor {
    BackgroundColor LightGray
    BorderColor Black
    FontColor Black
    FontSize 14
}

left to right direction


' Определение актёров
actor "Врач" as Doctor #lightblue
actor "Пациент" as Patient #lightgreen
actor "Родственник" as Relative #lightyellow
actor "Администратор" as Admin #lightcoral

' Случаи использования врача
usecase "Инициализирует систему для пациента" as UC1 #lightblue
usecase "Отслеживать параметры пациента <b>(?)</b>" as UC2 #lightblue
usecase "Получение уведомления о критической ситуации" as UC3 #lightblue
usecase "Чат с пациентом" as UC4 #lightblue
usecase "Доступ к базе данных своих пациентов" as UC20 #lightblue

' Случаи использования пациента
usecase "Мониторинг питания" as UC5 #lightgreen
usecase "Мониторинг физ. активности" as UC6 #lightgreen
usecase "История измерений\n(фильтр по дате и времени)" as UC7 #lightgreen
usecase "Мониторинг уровня глюкозы" as UC8 #lightgreen
usecase "Интерактивная шкала\nс цветовой индикацией" as UC9 #lightgreen
usecase "Добавление родственников <b>(или врач?)</b>" as UC10 #lightgreen

' Случаи использования родственника
usecase "Получение push-уведомлений о критических изменениях" as UC11 #lightyellow

' Случаи использования администратора
usecase "Управление конфигурацией системы" as UC12 #lightcoral
usecase "Добавление / удаление врачей" as UC13 #lightcoral

' Связи
Doctor -- UC1
Doctor -- UC2
Doctor -- UC3
Doctor -- UC4
Doctor -- UC20

Patient -- UC5
Patient -- UC6
Patient -- UC7
Patient -- UC8
Patient -- UC9
Patient -- UC10

Relative -- UC11

Admin -- UC12
Admin -- UC13

@enduml
